### ISSUE TITLE
[Issue]: <title> 运行webserver的main.py的时候报错 【python webserver/main.py】

### ISSUE THREAD

**Issue by PiggyAndrew** [KylinMountain/graphrag-server#17]
### Is there an existing issue for this?

- [ ] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

运行webserver的main.py的时候报错
报错内容
`Initializing /etc/webserver directory
Traceback (most recent call last):
  File "D:\graphragWebserver\graphrag\webserver\main.py", line 26, in <module>
    from webserver import gtypes
  File "C:\ProgramData\miniconda3\envs\graphragserver\lib\site-packages\webserver\__init__.py", line 17, in <module>
    run_command(["sudo", "mkdir", "-p", f"/etc/webserver/{folder}"])
  File "C:\ProgramData\miniconda3\envs\graphragserver\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\miniconda3\envs\graphragserver\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\miniconda3\envs\graphragserver\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
`
请问这是我安装操作的哪一步没有正确么？

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by KylinMountain** [comment]
try python -m webserver.main

**Comment by KylinMountain** [comment]
No reponse
