### ISSUE TITLE
[Feature Request]: <title>ubuntu系统执行索引命令报了一个关于window的错误

### ISSUE THREAD

**Issue by caoxinxiang123** [KylinMountain/graphrag-server#29]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this feature is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate feature request, not just a question. If this is a question, please use the Discussions area.

### Is your feature request related to a problem? Please describe.

命令是：
sudo docker run -v ./output:/app/output \
           -v ./input:/app/input \
           -v ./prompts:/app/prompts \
           -v ./settings.yaml:/app/settings.yaml \
           -v ./lancedb:/app/lancedb -p 20213:20213 kylinmountain/graphrag-server:0.3.1 python -m graphrag.index --root .

### Describe the solution you'd like

报错信息为：
openai.APITimeoutError: Request timed out.
03:54:29,80 graphrag.index.reporting.file_workflow_callbacks INFO Community Report Extraction Error details=None
03:54:29,80 graphrag.index.verbs.graph.report.strategies.graph_intelligence.run_graph_intelligence WARNING No report found for community: 7
03:54:29,86 datashaper.workflow.workflow INFO executing verb window
03:54:29,86 datashaper.workflow.workflow ERROR Error executing verb "window" in create_final_community_reports: 'community'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/datashaper/workflow/workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
  File "/usr/local/lib/python3.10/site-packages/datashaper/engine/verbs/window.py", line 73, in window
    window = __window_function_map[window_operation](input_table[column])
  File "/usr/local/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'community'
03:54:29,92 graphrag.index.reporting.file_workflow_callbacks INFO Error executing verb "window" in create_final_community_reports: 'community' details=None
03:54:29,92 graphrag.index.run ERROR error running workflow create_final_community_reports
Traceback (most recent call last):
  File "/app/graphrag/index/run.py", line 325, in run_pipeline
    result = await workflow.run(context, callbacks)
  File "/usr/local/lib/python3.10/site-packages/datashaper/workflow/workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
  File "/usr/local/lib/python3.10/site-packages/datashaper/workflow/workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
  File "/usr/local/lib/python3.10/site-packages/datashaper/engine/verbs/window.py", line 73, in window
    window = __window_function_map[window_operation](input_table[column])
  File "/usr/local/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'community'
03:54:29,93 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None
03:54:29,168 graphrag.index.cli ERROR Errors occurred during the pipeline run, see logs for more details.

**Comment by KylinMountain** [comment]
LLM访问不通吧？不能配置localhost作为llm的地址，得配置host的ip地址，不然docker内无法访问呢。
