### ISSUE TITLE
直接调用api请求报错

### ISSUE THREAD

**Issue by Maekfei** [KylinMountain/graphrag-server#3]
### Is there an existing issue for this?

- [ ] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

这是我的请求脚本，我的output文件夹构建索引和graph时 正常输出了json和parquet文件
import requests
from fastapi import HTTPException
def call_chat_completions_api(model, messages1):
    print('http://localhost:20213/docs')
    url = "http://localhost:20213/v1/chat/completions"  # 修改为你的API地址
    payload = {
  "messages": [
    {
      "content": "这篇文档讲了什么",
      "role": "user"
    }
  ],
  "model": '20240805-122042-global',
  "frequency_penalty": 0,
  "logit_bias": {
    "additionalProp1": 0,
    "additionalProp2": 0,
    "additionalProp3": 0
  },
  "logprobs": True,
  "max_tokens": 2000,
  "n": 0,
  "parallel_tool_calls": True,
  "presence_penalty": 0,
  "response_format": {
    "type": "text"
  },
  "seed": 0,
  "service_tier": "auto",
  "stop": "string",
  "stream": False,
  "stream_options": {},
  "temperature": 0.3,
  "tools": [
    {
      "name": "string",
      "description": "string"
    }
  ],
  "top_logprobs": 0,
  "top_p": 1.0,
  "user": "string"
    }

    try:
        print(requests.get("http://localhost:20213/v1/models").json())
        response = requests.post(url, json=payload)
        print(response)
        response.raise_for_status()  # Raise an exception for HTTP errors
        return response.json()
    except requests.RequestException as e:
        raise HTTPException(status_code=response.status_code, detail=str(e))

print(call_chat_completions_api('qwen2',"这篇文档讲了什么"))

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Logs and screenshots

报错如下
HTTPException: 500: 500 Server Error: Internal Server Error for url: http://localhost:20213/v1/chat/completions

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Cell In[19], line 49, in call_chat_completions_api(model, messages1)
     48 print(response)
---> 49 response.raise_for_status()  # Raise an exception for HTTP errors
     50 return response.json()

File /mnt/workspace/myenv/lib/python3.10/site-packages/requests/models.py:1021, in Response.raise_for_status(self)
   1020 if http_error_msg:
-> 1021     raise HTTPError(http_error_msg, response=self)

HTTPError: 500 Server Error: Internal Server Error for url: [http://localhost:20213/v1/chat/completions](https://584050-proxy-20213.dsw-gateway-cn-hangzhou.data.aliyun.com/v1/chat/completions)

During handling of the above exception, another exception occurred:

HTTPException                             Traceback (most recent call last)
Cell In[19], line 54
     51     except requests.RequestException as e:
     52         raise HTTPException(status_code=response.status_code, detail=str(e))
---> 54 print(call_chat_completions_api('qwen2',"这篇文档讲了什么"))

Cell In[19], line 52, in call_chat_completions_api(model, messages1)
     50     return response.json()
     51 except requests.RequestException as e:
---> 52     raise HTTPException(status_code=response.status_code, detail=str(e))

HTTPException: 500: 500 Server Error: Internal Server Error for url: [http://localhost:20213/v1/chat/completions](https://584050-proxy-20213.dsw-gateway-cn-hangzhou.data.aliyun.com/v1/chat/completions)

INFO:     127.0.0.1:37842 - "GET /v1/models HTTP/1.1" 200 OK
2024-08-05 12:22:00,467 - graphrag.query.context_builder.community_context - INFO - Computing community weights...
INFO:     127.0.0.1:37846 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/workspace/graphrag/./webserver/main.py", line 185, in chat_completions
    result = await global_search.asearch(prompt, conversation_history=conversation_history)
  File "/mnt/workspace/graphrag/./graphrag/query/structured_search/global_search/search.py", line 127, in asearch
    callback.on_map_response_start(context_chunks)  # type: ignore
AttributeError: 'NoneType' object has no attribute 'on_map_response_start'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/mnt/workspace/graphrag/./webserver/main.py", line 239, in chat_completions
    raise HTTPException(status_code=500, detail=e)
fastapi.exceptions.HTTPException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 88, in __call__
    response = await handler(request, exc)
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/fastapi/exception_handlers.py", line 15, in http_exception_handler
    return JSONResponse(
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/starlette/responses.py", line 196, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/starlette/responses.py", line 55, in __init__
    self.body = self.render(content)
  File "/mnt/workspace/graphrag/myenv2/lib/python3.10/site-packages/starlette/responses.py", line 199, in render
    return json.dumps(
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AttributeError is not JSON serializable
INFO:     127.0.0.1:38126 - "GET /v1/models HTTP/1.1" 200 OK
2024-08-05 12:22:44,129 - graphrag.query.context_builder.community_context - INFO - Computing community weights...
INFO:     127.0.0.1:38130 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/workspace/graphrag/./webserver/main.py", line 185, in chat_completions
    result = await global_search.asearch(prompt, conversation_history=conversation_history)
  File "/mnt/workspace/graphrag/./graphrag/query/structured_search/global_search/search.py", line 127, in asearch
    callback.on_map_response_start(context_chunks)  # type: ignore
AttributeError: 'NoneType' object has no attribute 'on_map_response_start'

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by Maekfei** [comment]
已找到无法返回值的原因 请求头里面stream必须是True 非流式会出错

**Comment by KylinMountain** [comment]
> 已找到无法返回值的原因 请求头里面stream必须是True 非流式会出错

非流式不会出错啊，你是最新代码吗？昨晚有一版修复，我之前忽略测试非流式的
