### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by w2001cy** [KylinMountain/graphrag-server#33]
When performing local operations, the main. py error is as follows：AttributeError: 'str' object has no attribute 'get'

**Comment by w2001cy** [comment]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "W:\Anaconda\envs\graph_stream\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\Anaconda\envs\graph_stream\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\Anaconda\envs\graph_stream\Lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "W:\Anaconda\envs\graph_stream\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "W:\Anaconda\envs\graph_stream\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "W:\Anaconda\envs\graph_stream\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "W:\Anaconda\envs\graph_stream\Lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "W:\Anaconda\envs\graph_stream\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "W:\Anaconda\envs\graph_stream\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "W:\Anaconda\envs\graph_stream\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "W:\Anaconda\envs\graph_stream\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "W:\Anaconda\envs\graph_stream\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "W:\Anaconda\envs\graph_stream\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "W:\Anaconda\envs\graph_stream\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "W:\Anaconda\envs\graph_stream\Lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\Anaconda\envs\graph_stream\Lib\site-packages\fastapi\routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\graphrag_stream\graphrag-server\webserver\main.py", line 523, in get_advice_question
    local_context = await switch_context(index=request.model)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\graphrag_stream\graphrag-server\webserver\main.py", line 569, in switch_context
    context_builder = await search.load_local_context(settings.data, text_embedder, token_encoder)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\graphrag_stream\graphrag-server\webserver\search\localsearch.py", line 40, in load_local_context
    vector_store_type = settings.embeddings.vector_store.get("type", VectorStoreType.LanceDB)  # type: ignore
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
INFO:     127.0.0.1:53204 - "POST /v1/advice_questions HTTP/1.1" 500 Internal Server Error

**Comment by KylinMountain** [comment]
这是建议提问时候触发的问题吗？

**Comment by w2001cy** [comment]
解决了  setting版本不一致的原因 0.5.0的setting跟0.4.0不太一样  感谢了

**Comment by KylinMountain** [comment]
你升级啦？现在不打算更新呢，ms一直在重构，简直浪费时间。。。
